./process: line 2: 40389 Segmentation fault: 11  src/bin/src $1 $2 $3
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./master.py", line 51, in run
    thread.send("connect " + str(self.index) + " " + self.address + ":" + str(self.port))
  File "./master.py", line 76, in send
    self.sock.send(str(s) + '\n')
error: [Errno 32] Broken pipe

